version: '3'
services:
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=fsky
      - MYSQL_PASSWORD=fsky
      - MYSQL_DATABASE=fsky
      - MYSQL_ROOT_PASSWORD=passw0rd
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./provision:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8607:80"
    links:
      - database:db